sudo: required
services:
  - docker
before_install:
  - sudo apt-get install jq
  # - docker pull homeassistant/amd64-builder
  - docker pull homeassistant/armhf-builder
env:
  - ADDON="Kuna"
script:
  - docker login -u $DOCKER_USER -p $DOCKER_PWD
  # - ./build.sh $ADDON
  - docker run --rm --privileged -v ~/.docker:/root/.docker homeassistant/amd64-builder --addon --all -t $ADDON -r https://github.com/hitchris/hassio-addons -b master -d hitchris